### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [MarcoASedano/jammming#1]
### Criteria 1: CRA Project Creation & Structure
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*:  Your file structure is good.  You made a CRA app and all of the components are properly located inside of folders, with the file paths working as well.  Nice work!

### Criteria 2: Data Flow
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You met the requirements for data flow within the app.  You did well working with Spotify and showed good understanding of how it worked.  Your search functionality was well done and your playlist manipulation was also great.  Nice work!

### Criteria 3: Syntax
* **Score Level**: 3/4 (Meets Expectations)
* *Comment(s)*: You hit upon all of the syntax requirements here.  You used className when applying classes and used JSX instead of pure HTML.  You added a reset.css properly and keys to each of the tracks in your track list.  There were some areas of improvement in the add and remove track methods.  I noticed that you directly modified state within your addTrack method, which is something that should be avoided in React.  You should copy any arrays you are modifying from state before setting them back to state as arrays are passed by reference and will be modified in place if not copied before manipulation.  Additionally, you could use a method like forEach or indexOf to check for existence of a track instead of using the basic for loop.  It isn't wrong by any means, but it would be cleaner.  Other than that, great job!

### Criteria 4: DRY Code/Style
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: You did well keeping your code "DRY."  One thing I would suggest would be to break out the base API url into its own variable.  This makes the code more maintainable if the base API url ever changes for any reason.  Great work!

### Overall Score: 15/16
Overall, you did a great job with this project.  You implemented all of the features of the project and wrote "DRY" code.  Your data flow through the app was great and you did a good job working with the Spotify API.  A lot of learners experience trouble when working with Spotify, so it is great to see that you were able to get it.  Awesome work!

**Comment by MarcoASedano** [comment]
Hi @tbergen1,

Regarding your comment about my addTrack/removeTrack methods, would the following code prevent modifying state in place? I've also tried to use indexOf to make it look a little cleaner:
```
addTrackToPlaylist(track) {
    let tracks = [];
    this.state.playlistTracks.forEach(track => tracks.push(track));

    let index = tracks.findIndex(curr => curr.id === track.id);
    if (index === -1) {
      tracks.push(track);
      this.setState({
        playlistTracks: tracks
      });
    }
  }
```

```
removeTrackFromPlaylist(track) {
    let tracks = [];
    this.state.playlistTracks.forEach(track => tracks.push(track));

    let index = tracks.findIndex(curr => curr.id === track.id);
    if (index !== -1) {
      tracks.splice(index, 1);
      this.setState({
        playlistTracks: tracks
      });
    }
  }
```

**Comment by tbergen1** [comment]
Any time you would copy the array like you did above you would be able to avoid modifying state directly.  An easier way would be to copy the array using the spread operator.  Something like this:

`
const tracks = [ ...this.state.playlistTracks ];
`
